
const KEY="jastech_unico_v2";
const OLD_KEY="jastech_unico_v1";
const defaults={name:"JasTech Recrutamento & Seleção",cnpj:"",location:"Carandaí/MG e região.",heroTitle:"Conectando talentos às melhores oportunidades.",heroText:"A JasTech aproxima empresas e profissionais e organiza as etapas de recrutamento e seleção.",whatsapp:"5531999999999",primary:"#1769ff",nav:"#071b3a",bg:"#f5f8fc",text:"#10213d",layout:"classic",buttonStyle:"rounded",mediaImage:"",mediaVideo:"",music:[],password:"1234",jobs:[{id:1,title:"Auxiliar Administrativo",area:"Administrativo",city:"Carandaí/MG",type:"Efetivo",active:true},{id:2,title:"Vendedor(a)",area:"Vendas",city:"Carandaí/MG",type:"Efetivo",active:true},{id:3,title:"Auxiliar de Produção",area:"Produção",city:"Região",type:"Efetivo",active:true}],candidates:[],companies:[],finance:{transactions:[]},stages:["Cadastro recebido","Triagem de currículo","Entrevista JasTech","Finalista / encaminhado para entrevista","Aprovado","Não aprovado"]};
function data(){
  try{
    if(window.__serverData)return window.__serverData;
    let raw=localStorage.getItem(KEY);
    if(!raw){ const old=localStorage.getItem(OLD_KEY); if(old){ raw=old; localStorage.setItem(KEY,old); } }
    const saved=JSON.parse(raw||"null");
    if(!saved)return structuredClone(defaults);
    const d={...structuredClone(defaults),...saved};
    d.jobs=Array.isArray(saved.jobs)?saved.jobs:structuredClone(defaults.jobs);
    d.jobs=d.jobs.map(j=>({...j,active:j.active===true||j.active===1||String(j.active).toLowerCase()==="true"}));
    d.candidates=Array.isArray(saved.candidates)?saved.candidates:[];
    d.companies=Array.isArray(saved.companies)?saved.companies:[];
    if(!saved.adminApprovalV2){d.jobs=d.jobs.map(j=>j.companyId&&!j.approvedByAdmin?{...j,active:false,approvedByAdmin:false,processStatus:"Solicitação recebida"}:j);d.adminApprovalV2=true;}
    d.stages=Array.isArray(saved.stages)&&saved.stages.length?saved.stages:structuredClone(defaults.stages);
    return d;
  }catch(e){return structuredClone(defaults)}
}
function save(d){window.__serverData=d;localStorage.setItem(KEY,JSON.stringify(d));fetch("/api/admin/state",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+(sessionStorage.jasAdminToken||"")},body:JSON.stringify(d)}).then(r=>r.json()).catch(()=>{})} 
async function syncServer(){try{const r=await fetch("/api/admin/state",{cache:"no-store",headers:{"Authorization":"Bearer "+(sessionStorage.jasAdminToken||"")}});if(!r.ok)return;const remote=await r.json();if(remote&&Array.isArray(remote.jobs)){window.__serverData=remote;localStorage.setItem(KEY,JSON.stringify(remote));refreshAdmin();}}catch(e){console.warn("Servidor indisponível",e)}}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function doLogin(){
  const user=document.getElementById("loginUser"), pass=document.getElementById("loginPass"), msg=document.getElementById("loginMsg");
  try{const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({user:user.value,password:pass.value})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Falha no login");sessionStorage.setItem("jasAdminToken",x.token);sessionStorage.setItem("jasLogin","1");msg.textContent="";enterDash();}catch(e){msg.textContent=e.message||"Usuário ou senha incorretos.";}
}
function enterDash(){
  document.getElementById("adminLogin").classList.add("hidden");
  document.getElementById("dashboard").classList.remove("hidden");
  loadEditor();refreshAdmin();syncServer();
  const el=document.getElementById("finDate");
  if(el&&!el.value)el.value=new Date().toISOString().slice(0,10);
}
function logout(){sessionStorage.removeItem("jasLogin");sessionStorage.removeItem("jasAdminToken");document.getElementById("adminLogin").classList.remove("hidden");document.getElementById("dashboard").classList.add("hidden")}
function showTab(id){["siteTab","designTab","jobsTab","processTab","candTab","compTab","financeTab","musicTab"].forEach(x=>document.getElementById(x).classList.toggle("hidden",x!==id))}
function loadEditor(){let d=data();editName.value=d.name;editCnpj.value=d.cnpj||"";editLocation.value=d.location;editHeroTitle.value=d.heroTitle;editHeroText.value=d.heroText;editWhats.value=d.whatsapp;colorPrimary.value=d.primary||"#1769ff";colorNav.value=d.nav||"#071b3a";colorBg.value=d.bg||"#f5f8fc";colorText.value=d.text||"#10213d";layoutChoice.value=d.layout||"classic";buttonStyle.value=d.buttonStyle||"rounded";renderMediaPreview()}
function saveSite(){let d=data();d.name=editName.value||d.name;d.cnpj=editCnpj.value||"";d.location=editLocation.value||d.location;d.heroTitle=editHeroTitle.value||d.heroTitle;d.heroText=editHeroText.value||d.heroText;d.whatsapp=editWhats.value.replace(/\D/g,"")||d.whatsapp;save(d);siteMsg.textContent="Informações salvas. Atualize o site público para visualizar.";}
function resetSite(){let d=data();Object.assign(d,{name:defaults.name,cnpj:defaults.cnpj,location:defaults.location,heroTitle:defaults.heroTitle,heroText:defaults.heroText,whatsapp:defaults.whatsapp});save(d);loadEditor();siteMsg.textContent="Informações restauradas."}
function addJob(){let d=data();if(!jobTitle.value.trim())return;d.jobs.push({id:Date.now(),title:jobTitle.value,area:jobArea.value,city:jobCity.value,type:jobType.value||"Efetivo",active:false,approvedByAdmin:false,processStatus:"Rascunho administrativo"});save(d);jobTitle.value=jobArea.value=jobCity.value=jobType.value="";refreshAdmin()}
function deleteJob(id){let d=data();d.jobs=d.jobs.filter(x=>x.id!==id);save(d);refreshAdmin()}
function toggleJob(id){let d=data(),x=d.jobs.find(x=>Number(x.id)===Number(id));if(!x)return;x.active=!Boolean(x.active);x.approvedByAdmin=x.active===true;x.processStatus=x.active?"Publicado pelo administrador":"Pausada pelo administrador";save(d);refreshAdmin();}
function fileToData(file){return new Promise((res,rej)=>{let r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
function saveDesign(){let d=data();d.primary=colorPrimary.value;d.nav=colorNav.value;d.bg=colorBg.value;d.text=colorText.value;d.layout=layoutChoice.value;d.buttonStyle=buttonStyle.value;let jobs=[];let img=mediaImage.files[0],vid=mediaVideo.files[0];if(img)jobs.push(fileToData(img).then(x=>d.mediaImage=x));if(vid)jobs.push(fileToData(vid).then(x=>d.mediaVideo=x));Promise.all(jobs).then(()=>{save(d);renderMediaPreview();designMsg.textContent="Aparência e mídia salvas."})}
function renderMediaPreview(){let d=data(),box=document.getElementById("mediaPreview"),out="";if(d.mediaImage)out+=`<img src="${d.mediaImage}" alt="Imagem">`;if(d.mediaVideo)out+=`<video src="${d.mediaVideo}" controls></video>`;box.innerHTML=out||"<span class='muted'>Nenhuma mídia cadastrada.</span>"}
function resetDesign(){let d=data();d.primary=defaults.primary;d.nav=defaults.nav;d.bg=defaults.bg;d.text=defaults.text;d.layout=defaults.layout;d.buttonStyle=defaults.buttonStyle;d.mediaImage="";d.mediaVideo="";save(d);loadEditor();designMsg.textContent="Aparência restaurada."}
function setCandidateStage(id){let d=data(),x=d.candidates.find(x=>x.id==id);if(!x)return;x.stage=document.getElementById('stage_'+id).value;x.feedback=document.getElementById('feedback_'+id).value;save(d);refreshAdmin()}
function setJobStatus(id){let d=data(),x=d.jobs.find(x=>x.id==id);if(!x)return;x.processStatus=document.getElementById('jobstatus_'+id).value;save(d);refreshAdmin()}
function publishCompanyJob(id){let d=data(),x=d.jobs.find(j=>Number(j.id)===Number(id));if(!x)return;x.active=true;x.approvedByAdmin=true;x.processStatus="Publicado pelo administrador";save(d);refreshAdmin()}
function setJobStatus(id){let d=data(),x=d.jobs.find(x=>x.id==id);if(!x)return;x.processStatus=document.getElementById('jobstatus_'+id).value;save(d);refreshAdmin()}
function refreshAdmin(){
let d=data();
statJobs.textContent=d.jobs.length;statCandidates.textContent=d.candidates.length;statCompanies.textContent=d.companies.length;statProcesses.textContent=d.candidates.length;
adminJobs.innerHTML=d.jobs.map(x=>{
 let c=x.companyId?d.companies.find(c=>Number(c.id)===Number(x.companyId)):null;
 let action=c&&!x.active?`<button class="btn primary" onclick="publishCompanyJob(${x.id})">🚀 Aprovar e publicar</button>`:`<button class="btn light" onclick="toggleJob(${x.id})">${x.active?"Pausar":"Ativar"}</button>`;
 return `<div class="box" style="margin:10px 0"><b>${esc(x.title)}</b> — ${esc(x.city)} — ${x.active?"Ativa":"Pausada"} ${c?`<span class="tag">🏢 ${esc(c.company)}</span>`:`<span class="tag">JasTech</span>`}<br>${c?`<small>Vaga vinculada ao cadastro da empresa • ${esc(c.email)}</small><br>`:""}<select id="jobstatus_${x.id}" style="max-width:420px"><option ${x.processStatus==="Solicitação recebida"?"selected":""}>Solicitação recebida</option><option ${x.processStatus==="Publicado automaticamente"?"selected":""}>Publicado automaticamente</option><option ${x.processStatus==="Em recrutamento"?"selected":""}>Em recrutamento</option><option ${x.processStatus==="Triagem em andamento"?"selected":""}>Triagem em andamento</option><option ${x.processStatus==="Finalistas encaminhados"?"selected":""}>Finalistas encaminhados</option><option ${x.processStatus==="Encerrado"?"selected":""}>Encerrado</option></select> <button class="btn light" onclick="setJobStatus(${x.id})">Salvar andamento</button> ${action} <button class="btn danger" onclick="deleteJob(${x.id})">Excluir</button></div>`;
}).join("");
adminCandidates.innerHTML=d.candidates.length?d.candidates.map(x=>{let opts=(d.stages||defaults.stages).map(st=>`<option ${x.stage===st?"selected":""}>${esc(st)}</option>`).join("");return `<div class="box" style="margin:12px 0"><button class="btn light" onclick="openCandidate(${x.id})"><b>${esc(x.name)}</b></button> — ${esc(x.jobTitle||x.role)}<br><small>${esc(x.email||"")} • ${esc(x.phone||"")} • ${esc(x.city||"")} • Cadastrado: ${formatDate(x.createdAt)}</small><div class="row" style="margin-top:10px"><label>Etapa atual<select id="stage_${x.id}">${opts}</select></label><label>Feedback para o candidato<textarea id="feedback_${x.id}">${esc(x.feedback||"")}</textarea></label></div><button class="btn primary" onclick="setCandidateStage(${x.id})">Salvar etapa e feedback</button></div>`}).join(""):"<p class='muted'>Nenhum candidato.</p>";
adminProcesses.innerHTML=d.candidates.length?d.candidates.map(x=>`<div class="box" style="margin:10px 0;display:flex;justify-content:space-between;gap:12px;align-items:center"><div><button class="btn light" onclick="openCandidate(${x.id})"><b>${esc(x.name)}</b></button><br><small>${esc(x.jobTitle||x.role||"Vaga não informada")} • ${esc(x.stage||"Cadastro recebido")} • ${formatDate(x.createdAt)}</small></div><span class="tag">${esc(x.stage||"Cadastro recebido")}</span></div>`).join(""):"<p class='muted'>Nenhum processo.</p>";
refreshFinance();
adminCompanies.innerHTML=d.companies.length?d.companies.map(c=>{let js=d.jobs.filter(j=>Number(j.companyId)===Number(c.id)||((c.jobs||[]).map(Number).includes(Number(j.id))));return `<div class="box" style="margin:12px 0"><b>🏢 ${esc(c.company)}</b> <span class="tag">${c.paid===true?"✅ Pago":"⚠️ Não pago"}</span><br><small>${esc(c.email)} • ${esc(c.contact)} • ${esc(c.phone)}</small><div style="margin-top:8px">${c.paid===true?"<span class='tag'>Pagamento confirmado</span>":`<button class="btn danger" onclick="deleteUnpaidCompany(${c.id})">🗑️ Excluir empresa não paga</button>`}</div>${js.length?js.map(j=>{let cand=d.candidates.filter(x=>Number(x.jobId)===Number(j.id));let fin=cand.filter(x=>x.stage==="Finalista / encaminhado para entrevista"||x.stage==="Aprovado");let publish=j.active?`<span class="tag">✅ Publicada pelo administrador</span>`:`<button class="btn primary" onclick="publishCompanyJob(${j.id})">🚀 Publicar esta vaga</button>`;return `<div class="box" style="margin-top:10px;cursor:pointer" onclick="this.classList.toggle('expanded')"><b>💼 ${esc(j.title)}</b><p>Status: <strong>${j.active?"Publicada":"Aguardando aprovação"}</strong> • Inscritos: <strong>${cand.length}</strong> • Finalistas: <strong>${fin.length}</strong> • Aprovados: <strong>${cand.filter(x=>x.stage==="Aprovado").length}</strong></p><p class="muted">Clique para ver os dados completos da solicitação.</p><div style="padding:10px 0"><p><b>Cidade:</b> ${esc(j.city||"Não informada")} &nbsp; <b>Tipo:</b> ${esc(j.type||"Não informado")} &nbsp; <b>Quantidade:</b> ${esc(j.quantity||1)}</p><p><b>Salário/benefícios:</b> ${esc(j.salary||"Não informado")}</p><p><b>Requisitos:</b> ${esc(j.requirements||"Não informado")}</p><p><b>Status:</b> ${esc(j.processStatus||"Solicitação recebida")}</p>${publish}</div></div>`}).join(""):`<p class="muted">Nenhuma vaga vinculada.</p>`}</div>`}).join(""):"<p class='muted'>Nenhuma empresa.</p>";
}
function formatDate(v){if(!v)return "Data não informada";try{return new Date(v).toLocaleString("pt-BR")}catch(e){return String(v)}}
function openCandidate(id){let d=data(),x=d.candidates.find(c=>Number(c.id)===Number(id));if(!x)return;let j=d.jobs.find(j=>Number(j.id)===Number(x.jobId));let c=j&&j.companyId?d.companies.find(c=>Number(c.id)===Number(j.companyId)):null;document.getElementById("candidateModalTitle").textContent=x.name||"Candidato";document.getElementById("candidateModalBody").innerHTML=`<div class="box"><p><b>Nome:</b> ${esc(x.name||"Não informado")}</p><p><b>E-mail:</b> ${esc(x.email||"Não informado")}</p><p><b>WhatsApp:</b> ${esc(x.phone||"Não informado")}</p><p><b>Cidade:</b> ${esc(x.city||"Não informado")}</p><p><b>Cargo pretendido:</b> ${esc(x.role||"Não informado")}</p><p><b>Área:</b> ${esc(x.area||"Não informada")}</p><p><b>Vaga:</b> ${esc(x.jobTitle||x.role||"Não informada")}</p><p><b>Empresa contratante:</b> ${esc(c?.company||"Não informada")}</p><p><b>Fase:</b> ${esc(x.stage||"Cadastro recebido")}</p><p><b>Data do cadastro:</b> ${formatDate(x.createdAt)}</p><p><b>Experiência:</b><br>${esc(x.experience||"Não informada")}</p><p><b>Currículo:</b> ${esc(x.resume||"Não enviado")}</p><p><b>Feedback:</b><br>${esc(x.feedback||"Nenhum feedback registrado")}</p></div>`;document.getElementById("candidateModal").style.display="flex"}
function closeCandidate(){document.getElementById("candidateModal").style.display="none"}
function deleteUnpaidCompany(id){let d=data(),c=d.companies.find(c=>Number(c.id)===Number(id));if(!c||c.paid===true){alert("Esta empresa está marcada como paga e não pode ser excluída por esta opção.");return}if(!confirm(`Excluir a empresa ${c.company||""} e suas vagas?`))return;d.companies=d.companies.filter(c=>Number(c.id)!==Number(id));d.jobs=d.jobs.filter(j=>Number(j.companyId)!==Number(id));save(d);refreshAdmin()}

function moneyBR(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function financeData(d){if(!d.finance||typeof d.finance!=="object")d.finance={transactions:[]};if(!Array.isArray(d.finance.transactions))d.finance.transactions=[];return d.finance}
function addFinanceTransaction(){
 let d=data(),f=financeData(d),type=document.getElementById("finType").value,amount=parseFloat(document.getElementById("finAmount").value),desc=document.getElementById("finDesc").value.trim(),date=document.getElementById("finDate").value;
 if(!(amount>0)||!desc){financeMsg.textContent="Informe valor e descrição.";return}
 let category=document.getElementById("finCategory").value; f.transactions.unshift({id:Date.now(),type,category,amount,description:desc,date:date||new Date().toISOString().slice(0,10),createdAt:new Date().toISOString()});
 save(d);document.getElementById("finAmount").value="";document.getElementById("finDesc").value="";financeMsg.textContent="Movimentação lançada no caixa.";refreshFinance();
}
function deleteFinanceTransaction(id){let d=data(),f=financeData(d);f.transactions=f.transactions.filter(x=>Number(x.id)!==Number(id));save(d);refreshFinance()}
function setCompanyPaid(id,paid){
 let d=data(),c=d.companies.find(x=>Number(x.id)===Number(id));if(!c)return;
 c.paid=!!paid;c.paidAt=paid?new Date().toISOString():null;
 save(d);refreshAdmin();refreshFinance();
}
function saveCompanyMessage(c,text,type){
 if(!c)return false;
 text=(text||"").trim();
 if(!text)return false;
 if(!Array.isArray(c.messages))c.messages=[];
 c.messages.unshift({id:Date.now()+Math.floor(Math.random()*1000),type:type||"mensagem",text,createdAt:new Date().toISOString(),read:false});
 return true;
}
function defaultPendingMessage(c){return `Olá, ${c.company||""}! Tudo bem? Identificamos que há um pagamento pendente junto à JasTech. Pedimos, por gentileza, que verifique sua cobrança e, se possível, regularize o pagamento. Caso já tenha realizado o pagamento, por favor desconsidere esta mensagem. Agradecemos a atenção e permanecemos à disposição. — Equipe JasTech`}
function defaultPaidMessage(c){return `Olá, ${c.company||""}! A JasTech agradece pelo pagamento realizado. Ficamos muito felizes em contar com sua parceria e confiança. Muito obrigado! Permanecemos à disposição sempre que precisar. — Equipe JasTech`}
function sendCompanyCharge(id){let d=data(),c=d.companies.find(x=>Number(x.id)===Number(id));if(!c)return;let amount=parseFloat(document.getElementById("chargeAmount_"+id).value)||0,due=document.getElementById("chargeDue_"+id).value,msg=document.getElementById("chargeMsg_"+id).value.trim();let methods={pix:document.getElementById("payPix_"+id).checked,credit:document.getElementById("payCredit_"+id).checked,debit:document.getElementById("payDebit_"+id).checked};if(!msg)msg="Olá! Identificamos um pagamento pendente junto à JasTech. Por favor, verifique sua cobrança. Caso já tenha pago, desconsidere esta mensagem. Obrigado!";if(!methods.pix&&!methods.credit&&!methods.debit){alert("Selecione pelo menos uma forma de pagamento.");return}c.paymentAmount=amount;c.paymentDue=due;c.pixInfo=document.getElementById("pixInfo_"+id).value.trim();c.cardLink=document.getElementById("cardLink_"+id).value.trim();c.paymentMethods=methods;if(!Array.isArray(c.messages))c.messages=[];c.messages.unshift({id:Date.now(),type:"cobranca",text:msg,amount,due,methods,pixInfo:c.pixInfo,cardLink:c.cardLink,createdAt:new Date().toISOString(),read:false});save(d);alert("Cobrança enviada para o perfil de "+(c.company||"empresa")+".");refreshFinance()}
function sendAutomaticCompanyMessage(id,type){let d=data(),c=d.companies.find(x=>Number(x.id)===Number(id));if(!c)return;let text=(type==="pago"?defaultPaidMessage(c):defaultPendingMessage(c));let field=document.getElementById("autoMsg_"+type+"_"+id);if(field&&field.value.trim())text=field.value.trim();if(!saveCompanyMessage(c,text,type==="pago"?"agradecimento":"cobranca"))return;save(d);alert("Mensagem enviada somente para "+(c.company||"esta empresa")+".");refreshFinance()}
function sendAutomaticToAll(status){let d=data(),companies=(d.companies||[]).filter(c=>status==="pago"?c.paid===true:c.paid!==true);if(!companies.length){alert(status==="pago"?"Nenhuma empresa paga cadastrada.":"Nenhuma empresa pendente cadastrada.");return}let field=document.getElementById("bulkMsg_"+status),template=field&&field.value.trim();if(!template)template=status==="pago"?"Olá! A JasTech agradece pelo pagamento realizado. Muito obrigado pela parceria e confiança. Permanecemos à disposição. — Equipe JasTech":"Olá! Identificamos um pagamento pendente junto à JasTech. Pedimos, por gentileza, que verifique sua cobrança e regularize o pagamento quando possível. Caso já tenha pago, desconsidere esta mensagem. Agradecemos a atenção. — Equipe JasTech";companies.forEach(c=>saveCompanyMessage(c,template.replace(/\{empresa\}/gi,c.company||""),status==="pago"?"agradecimento":"cobranca"));save(d);alert(`Mensagem enviada individualmente para ${companies.length} empresa(s) ${status==="pago"?"paga(s)":"pendente(s)"}.`);refreshFinance()}
function openIndividualMessageForCompany(id){
 openIndividualMessagePicker();
 const sel=document.getElementById("individualCompanySelect"); if(sel){sel.value=String(id);loadIndividualMessageTemplate();}
}
function openIndividualMessagePicker(){
 const d=data(), list=(d.companies||[]);
 const modal=document.getElementById("individualMessageModal"), sel=document.getElementById("individualCompanySelect");
 if(!modal||!sel){alert("Área de mensagem individual não encontrada.");return}
 sel.innerHTML=list.length?list.map(c=>`<option value="${c.id}">${esc(c.company||"Empresa")} — ${c.paid===true?"PAGA":"PENDENTE"} — ${moneyBR(c.paymentAmount||0)}</option>`).join(""):`<option value="">Nenhuma empresa cadastrada</option>`;
 modal.style.display="block"; loadIndividualMessageTemplate();
}
function closeIndividualMessagePicker(){const m=document.getElementById("individualMessageModal");if(m)m.style.display="none"}
function loadIndividualMessageTemplate(){
 const d=data(), id=document.getElementById("individualCompanySelect")?.value, c=(d.companies||[]).find(x=>String(x.id)===String(id)), field=document.getElementById("individualMessageText");
 if(!c||!field)return; field.value=c.paid===true?defaultPaidMessage(c):defaultPendingMessage(c);
}
function sendSelectedIndividualMessage(){
 const d=data(), id=document.getElementById("individualCompanySelect")?.value, c=(d.companies||[]).find(x=>String(x.id)===String(id)), field=document.getElementById("individualMessageText");
 if(!c){alert("Selecione uma empresa.");return}
 const text=(field?.value||"").trim(); if(!text){alert("Digite uma mensagem.");return}
 const type=c.paid===true?"agradecimento":"cobranca";
 if(!saveCompanyMessage(c,text,type)){alert("Não foi possível salvar a mensagem.");return}
 save(d); const st=document.getElementById("individualMessageStatus"); if(st)st.textContent="Mensagem enviada somente para "+(c.company||"esta empresa")+"."; alert("Mensagem enviada somente para "+(c.company||"esta empresa")+"."); refreshFinance();
}
function editCompanyMessage(id,status){let d=data(),c=d.companies.find(x=>Number(x.id)===Number(id));if(!c)return;let text=prompt("Digite a mensagem que deseja enviar para "+(c.company||"empresa")+":",status==="pago"?defaultPaidMessage(c):defaultPendingMessage(c));if(text===null)return;if(!text.trim()){alert("Digite uma mensagem.");return}saveCompanyMessage(c,text,status==="pago"?"agradecimento":"cobranca");save(d);alert("Mensagem enviada individualmente.");refreshFinance()}

function toggleFinancePanel(id,btn){const el=document.getElementById(id);if(!el)return false;const willOpen=!el.classList.contains('open');el.classList.toggle('open',willOpen);if(btn){btn.textContent=willOpen?(id==='companiesFinanceBody'?'Ocultar empresas ▴':'Ocultar cobranças ▴'):(id==='companiesFinanceBody'?'Ver empresas ▾':'Ver cobranças ▾');}return willOpen;}
function toggleFinanceBox(id){return toggleFinancePanel(id,null)}
function openFinanceBox(id,btn){return toggleFinancePanel(id,btn)}
function refreshFinance(){
 let d=data(),f=financeData(d),ins=f.transactions.filter(x=>x.type==="entrada").reduce((a,x)=>a+Number(x.amount||0),0),outs=f.transactions.filter(x=>x.type==="saida").reduce((a,x)=>a+Number(x.amount||0),0);
 let paidCompanies=(d.companies||[]).filter(c=>c.paid===true),pending=(d.companies||[]).filter(c=>c.paid!==true);
 let companyRevenue=paidCompanies.reduce((a,c)=>a+Number(c.paymentAmount||0),0),pendingTotal=pending.reduce((a,c)=>a+Number(c.paymentAmount||0),0);
 document.getElementById("finIn").textContent=moneyBR(ins+companyRevenue);document.getElementById("finPaid").textContent=paidCompanies.length+" empresas";document.getElementById("finPaidTotal").textContent=moneyBR(companyRevenue)+" pago";document.getElementById("finOut").textContent=moneyBR(outs);document.getElementById("finBalance").textContent=moneyBR(ins+companyRevenue-outs);document.getElementById("finPending").textContent=pending.length;document.getElementById("finPendingTotal").textContent=moneyBR(pendingTotal)+" pendente";
 let fc=document.getElementById("financeCompanies"),pendingRows=pending.map(c=>`<tr><td><b>${esc(c.company||"Empresa")}</b></td><td>${esc(c.email||"")}</td><td>${esc(c.contact||"")}</td><td>${c.paymentDue?formatDate(c.paymentDue):"—"}</td><td><b>${moneyBR(c.paymentAmount||0)}</b></td><td><button class="btn primary" onclick="sendAutomaticCompanyMessage(${c.id},'pendente')">📨 Enviar mensagem automática</button><button class="btn light" onclick="editCompanyMessage(${c.id},'pendente')">✏️ Personalizar mensagem</button></td></tr>`).join("");
 let paidRows=paidCompanies.map(c=>`<tr><td><b>${esc(c.company||"Empresa")}</b></td><td>${esc(c.email||"")}</td><td>${esc(c.contact||"")}</td><td>${c.paidAt?formatDate(c.paidAt):"—"}</td><td><b>${moneyBR(c.paymentAmount||0)}</b></td><td><button class="btn primary" onclick="sendAutomaticCompanyMessage(${c.id},'pago')">🙏 Enviar agradecimento automático</button><button class="btn light" onclick="editCompanyMessage(${c.id},'pago')">✏️ Personalizar mensagem</button></td></tr>`).join("");
 let pendingSummary=document.getElementById("pendingSummaryFinance");
 if(pendingSummary) pendingSummary.innerHTML=`<div><span class="mini">Empresas pendentes</span><strong>${pending.length}</strong></div><div><span class="mini">Valor pendente</span><strong>${moneyBR(pendingTotal)}</strong></div><div><span class="mini">Empresas pagas</span><strong>${paidCompanies.length}</strong></div><div><span class="mini">Valor pago</span><strong>${moneyBR(companyRevenue)}</strong></div><div style="grid-column:1/-1;overflow:auto"><h4 style="margin:10px 0">⚠️ Empresas pendentes</h4>${pending.length?`<table class="pendingTable"><thead><tr><th>Empresa</th><th>E-mail</th><th>Contato</th><th>Vencimento</th><th>Valor pendente</th><th>Mensagem</th></tr></thead><tbody>${pendingRows}</tbody></table>`:`<p class="muted">Nenhuma empresa pendente.</p>`}<h4 style="margin:18px 0 10px">✅ Empresas pagas</h4>${paidCompanies.length?`<table class="pendingTable"><thead><tr><th>Empresa</th><th>E-mail</th><th>Contato</th><th>Pagamento</th><th>Valor pago</th><th>Mensagem</th></tr></thead><tbody>${paidRows}</tbody></table>`:`<p class="muted">Nenhuma empresa paga.</p>`}</div>`;
 let bulk=document.getElementById("financeBulkMessages");
 if(bulk) bulk.innerHTML=`<div class="bulkMsgBox"><h3 style="margin-top:0">📨 Mensagens automáticas individuais</h3><p class="mini">As mensagens são enviadas separadamente e ficam no perfil individual de cada empresa. Você pode enviar para todas de um grupo ou escolher uma por uma.</p><div class="row"><label style="flex:1"><b>Mensagem para todas as PENDENTES</b><textarea id="bulkMsg_pendente">Olá! Identificamos um pagamento pendente junto à JasTech. Pedimos, por gentileza, que verifique sua cobrança e regularize o pagamento quando possível. Caso já tenha pago, desconsidere esta mensagem. Agradecemos a atenção. — Equipe JasTech</textarea><button class="btn primary" onclick="sendAutomaticToAll('pendente')">📨 Enviar para TODAS as pendentes</button></label><label style="flex:1"><b>Mensagem para todas as PAGAS</b><textarea id="bulkMsg_pago">Olá! A JasTech agradece pelo pagamento realizado. Muito obrigado pela parceria e confiança. Permanecemos à disposição. — Equipe JasTech</textarea><button class="btn primary" onclick="sendAutomaticToAll('pago')">🙏 Enviar para TODAS as pagas</button></label></div></div>`;
 fc.innerHTML=(d.companies||[]).length?d.companies.map(c=>`<div class="box" style="margin:9px 0"><div class="companyRow"><div class="companyData"><b>🏢 ${esc(c.company||"Empresa")}</b><br><span class="mini">${esc(c.email||"")} • ${esc(c.contact||"")}</span>${c.paymentAmount?`<br><span class="mini">Valor: <b>${moneyBR(c.paymentAmount)}</b></span>`:""}<br><span class="${c.paid===true?'statusPaid':'statusPending'}">${c.paid===true?'✅ PAGO':'⚠️ PENDENTE'}</span></div><div class="companyMsgActions">${c.paid===true?`<button class="btn light" onclick="setCompanyPaid(${c.id},false)">Marcar pendente</button><button class="btn primary" onclick="sendAutomaticCompanyMessage(${c.id},'pago')">🙏 Agradecimento automático</button><button class="btn light" onclick="editCompanyMessage(${c.id},'pago')">✏️ Personalizar</button>`:`<button class="btn primary" onclick="setCompanyPaid(${c.id},true)">Confirmar pagamento</button><button class="btn primary" onclick="sendAutomaticCompanyMessage(${c.id},'pendente')">📨 Mensagem automática</button><button class="btn light" onclick="editCompanyMessage(${c.id},'pendente')">✏️ Personalizar</button>`}</div></div><div class="companyDetail"><details><summary>Ver todos os dados e cobrança</summary><div class="payBox"><p><b>Empresa:</b> ${esc(c.company||"")}<br><b>E-mail:</b> ${esc(c.email||"")}<br><b>Contato:</b> ${esc(c.contact||"")}<br><b>Status:</b> ${c.paid===true?'Pago':'Pendente'}<br><b>Valor:</b> ${moneyBR(c.paymentAmount||0)}<br><b>Vencimento:</b> ${c.paymentDue?formatDate(c.paymentDue):'—'}${c.paidAt?`<br><b>Pago em:</b> ${formatDate(c.paidAt)}`:''}</p><label>Valor da cobrança (R$)<input id="chargeAmount_${c.id}" type="number" min="0" step="0.01" value="${Number(c.paymentAmount||0)||''}"></label><label>Vencimento<input id="chargeDue_${c.id}" type="date" value="${c.paymentDue||''}"></label><label>Mensagem de cobrança<textarea id="chargeMsg_${c.id}" placeholder="Digite a cobrança..."></textarea></label><div class="row"><label><input id="payPix_${c.id}" type="checkbox" ${c.paymentMethods?.pix!==false?'checked':''}> PIX</label><label><input id="payCredit_${c.id}" type="checkbox" ${c.paymentMethods?.credit!==false?'checked':''}> Crédito</label><label><input id="payDebit_${c.id}" type="checkbox" ${c.paymentMethods?.debit!==false?'checked':''}> Débito</label></div><div class="row"><label>Chave PIX / instruções<input id="pixInfo_${c.id}" value="${esc(c.pixInfo||'')}"></label><label>Link cartão<input id="cardLink_${c.id}" value="${esc(c.cardLink||'')}"></label></div><button class="btn primary" onclick="sendCompanyCharge(${c.id})">📨 Enviar cobrança no login</button></div></details></div></div>`).join(""):"<p class='muted'>Nenhuma empresa cadastrada.</p>";
 let rows=f.transactions.map(x=>`<tr><td>${formatDate(x.date)}</td><td>${x.type==="entrada"?'<span class="moneyIn">Entrada</span>':'<span class="moneyOut">Saída</span>'}</td><td><span class="expenseBadge">${esc(x.category||"Outros")}</span></td><td>${esc(x.description)}</td><td>${moneyBR(x.amount)}</td><td><button class="btn danger" onclick="deleteFinanceTransaction(${x.id})">Excluir</button></td></tr>`).join("");
 document.getElementById("financeTransactions").innerHTML=f.transactions.length?`<div style="overflow:auto"><table class="financeTable"><thead><tr><th>Data</th><th>Tipo</th><th>Categoria</th><th>Descrição</th><th>Valor</th><th>Ação</th></tr></thead><tbody>${rows}</tbody></table></div>`:"<p class='muted'>Nenhuma movimentação lançada.</p>";
 let fm=document.getElementById("financeMessages"),msgs=[];(d.companies||[]).forEach(c=>(c.messages||[]).forEach(m=>msgs.push({...m,company:c.company,email:c.email,paid:c.paid===true})));msgs.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));fm.innerHTML=msgs.length?msgs.map(m=>`<div class="messageCard"><b>🏢 ${esc(m.company)}</b> <span class="mini">${m.paid?'✅ Paga':'⚠️ Pendente'} • ${esc(m.email||"")} • ${formatDate(m.createdAt)}</span><p>${esc(m.text)}</p><p class="mini">${m.amount?`Valor: <b>${moneyBR(m.amount)}</b> • `:""}${m.due?`Vencimento: ${formatDate(m.due)} • `:""}Tipo: ${m.type||'mensagem'}</p></div>`).join(""):"<p class='muted'>Nenhuma mensagem enviada.</p>";
}

async function syncAdminServer(){try{const r=await fetch("/api/admin/state",{cache:"no-store",headers:{"Authorization":"Bearer "+(sessionStorage.jasAdminToken||"")}});if(!r.ok)return;const remote=await r.json();window.__serverData=remote;localStorage.setItem(KEY,JSON.stringify(remote));if(sessionStorage.jasLogin==="1"){loadEditor();refreshAdmin();}}catch(e){console.warn(e)}}
function data(){try{return window.__serverData||JSON.parse(localStorage.getItem(KEY)||"null")||structuredClone(defaults)}catch(e){return structuredClone(defaults)}}
function save(d){window.__serverData=d;localStorage.setItem(KEY,JSON.stringify(d));fetch("/api/admin/state",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+(sessionStorage.jasAdminToken||"")},body:JSON.stringify(d)}).then(r=>r.json()).catch(()=>{});}
syncAdminServer();
if(sessionStorage.jasLogin==="1") enterDash();
window.addEventListener("storage",e=>{if(e.key===KEY||e.key===OLD_KEY){if(sessionStorage.jasLogin==="1")refreshAdmin();}});

document.addEventListener("DOMContentLoaded",()=>{
  const p=document.getElementById("loginPass");
  if(p) p.addEventListener("keydown",e=>{if(e.key==="Enter")doLogin()});
  if(sessionStorage.getItem("jasLogin")==="1") enterDash();
});
function ensureMusic(d){if(!Array.isArray(d.music))d.music=[];return d}
function ytId(url){try{const u=new URL(url);if(u.hostname.includes('youtu.be'))return u.pathname.slice(1).split('/')[0];if(u.hostname.includes('youtube.com')){if(u.pathname==='/watch')return u.searchParams.get('v');if(u.pathname.startsWith('/shorts/'))return u.pathname.split('/')[2];if(u.pathname.startsWith('/embed/'))return u.pathname.split('/')[2]}}catch(e){}return ''}
function searchYouTube(){const q=(document.getElementById('ytSearch')?.value||'').trim();if(!q){document.getElementById('musicMsg').textContent='Digite o nome da música ou artista para pesquisar.';return}window.open('https://www.youtube.com/results?search_query='+encodeURIComponent(q),'_blank','noopener');}
function addYouTubeMusic(){let d=ensureMusic(data()), url=(document.getElementById('ytUrl')?.value||'').trim(), id=ytId(url), title=(document.getElementById('ytTitle')?.value||'').trim();if(!id){document.getElementById('musicMsg').textContent='Cole um link válido do YouTube.';return}if(!title)title='Música do YouTube';d.music.push({id:Date.now(),type:'youtube',videoId:id,title,url,active:true,createdAt:new Date().toISOString()});save(d);document.getElementById('ytUrl').value='';document.getElementById('ytTitle').value='';document.getElementById('musicMsg').textContent='Música do YouTube adicionada à playlist.';renderAdminMusic();}
function addMP3Music(){const file=document.getElementById('mp3File')?.files?.[0], title=(document.getElementById('mp3Title')?.value||'').trim();if(!file){document.getElementById('musicMsg').textContent='Selecione um arquivo MP3.';return}if(file.size>8*1024*1024){document.getElementById('musicMsg').textContent='O MP3 precisa ter no máximo 8 MB.';return}const reader=new FileReader();reader.onload=()=>{let d=ensureMusic(data());d.music.push({id:Date.now(),type:'mp3',title:title||file.name.replace(/\.mp3$/i,''),src:reader.result,active:true,createdAt:new Date().toISOString()});save(d);document.getElementById('mp3File').value='';document.getElementById('mp3Title').value='';document.getElementById('musicMsg').textContent='MP3 adicionado à playlist.';renderAdminMusic()};reader.readAsDataURL(file)}
function renderAdminMusic(){const el=document.getElementById('adminMusicList');if(!el)return;const d=ensureMusic(data());el.innerHTML=d.music.length?d.music.map((m,i)=>`<div class="messageCard companyRow"><div class="companyData"><b>${m.type==='youtube'?'▶️':'🎵'} ${esc(m.title)}</b><div class="mini">${m.type==='youtube'?'YouTube':'MP3'} • ${m.active!==false?'Ativa':'Desativada'}</div></div><div class="companyMsgActions"><button class="btn light" onclick="toggleMusic(${m.id})">${m.active!==false?'⏸️ Desativar':'▶️ Ativar'}</button><button class="btn danger" onclick="deleteMusic(${m.id})">🗑️ Excluir</button></div></div>`).join(''):'<p class="muted">Nenhuma música adicionada.</p>'}
function toggleMusic(id){let d=ensureMusic(data()),m=d.music.find(x=>Number(x.id)===Number(id));if(m)m.active=m.active===false;save(d);renderAdminMusic()}
function deleteMusic(id){let d=ensureMusic(data());d.music=d.music.filter(x=>Number(x.id)!==Number(id));save(d);renderAdminMusic()}
renderAdminMusic();

// Controles do Financeiro: um único listener por botão, sem onclick duplicado.
document.addEventListener("DOMContentLoaded", function(){
  function wireFinanceToggle(btnId, bodyId, openText, closeText){
    const btn=document.getElementById(btnId), body=document.getElementById(bodyId);
    if(!btn || !body || btn.dataset.wired === "1") return;
    btn.dataset.wired="1";
    const setState=(open)=>{
      body.classList.toggle("open", open);
      btn.setAttribute("aria-expanded", open ? "true" : "false");
      btn.textContent=open ? closeText : openText;
    };
    setState(false);
    btn.addEventListener("click", function(ev){
      ev.preventDefault(); ev.stopPropagation();
      setState(!body.classList.contains("open"));
    }, {capture:false});
  }
  wireFinanceToggle("companiesToggleBtn","companiesFinanceBody","Ver empresas ▾","Ocultar empresas ▴");
  wireFinanceToggle("messagesToggleBtn","messagesFinanceBody","Ver cobranças ▾","Ocultar cobranças ▴");
});
